[server.bot-acl]
# Allow rust team members defined in https://github.com/rust-lang/team
rust-teams = true
# The list of GitHub users allowed to interact with the GitHub bot
# You can mix usernames and teams
github = []

[server.labels]
# Remove all labels matching this regex when applying new labels
remove = "^S-"
# Automatically apply the following labels to issues/pull requests
experiment-queued = "S-waiting-on-crater"
experiment-completed = "S-waiting-on-review"

# This section contains the list of tested crates when defining an experiment
# with `--crate-select demo`.

[demo-crates]
crates = ["lazy_static"]
github-repos = ["brson/hello-rs"]
local-crates = []

[sandbox]
# Maximum amount of RAM allowed during builds
memory-limit = "1536M"  # 1.5G
# Restrictions on the amount of information stored in build logs
build-log-max-size = "5M"
build-log-max-lines = 10000


# These sections allows to customize how crater treats specific crates/repos
#
# The available options for each crate/repo are:
#  - skip            (bool): ignore this crate/repo
#  - skip-tests      (bool): don't run tests in this crate/repo
#  - quiet           (bool): don't kill after two minutes without output
#  - broken          (bool): treat a Crater error on this crate/repo as a build
#                            failure (typically the crate is broken in an
#                            unusual way and we want to indicate the failure
#                            is 'permissible', while still building it if the
#                            failure is resolved in the future)

# Please add a comment along with each entry explaining the reasons of the
# changes, thanks!

[crates]
# crate_name = { option = true }
actix = { skip-tests = true } # flaky test
ai = { skip-tests = true } # may fail due to randomness
alumina = { skip = true } # flaky build
atlas-coverage-core = { skip-tests = true } # flaky tests
bitrust = { skip = true } # buggy build script
caesarlib = { skip-tests = true } # flaky test
catboost2-sys = { skip = true } # requires rustfmt
cc = { skip-tests = true } # flaky test
chef_api = { skip-tests = true } # flaky tests
ci_info = { skip-tests = true } # flaky tests
coinnect = { skip-tests = true } # flaky test
csv = { skip-tests = true } # flaky test
ctx = { skip-tests = true } # tests depends on timing
diskvec = { skip-tests = true } # flaky test
esprit = { broken = true } # broken Cargo.toml
fe_session = { skip-tests = true } # flaky test
feed = { skip-tests = true } # flaky test
fftw = { slow = true } # build time close to 2 minutes
fine_grained = { skip-tests = true } # flaky tests
gcc = { skip-tests = true } # flaky test
gear = { skip = true } # flaky build
geocode = { skip-tests = true } # depends on network
glib = { slow = true } # tests slow to run
guerrilla = { skip-tests = true } # flaky tests
hashconsing = { skip-tests = true } # flaky test
hyperdav = { skip-tests = true } # relies on an external service
idx = { skip-tests = true } # depends on filesystem
image-stream = { skip-tests = true } # depends on network
ipc-channel = { slow = true } # tests slow to run
jemalloc-ctl = { skip-tests = true } # flaky tests
ledger-transport-zemu = { skip = true } # buggy build script
libfuzzy-sys = { skip = true } # flaky build
loadconf = { skip-tests = true } # flaky test
loaded_dice = { skip-tests = true } # may fail due to randomness
lockless = { skip-tests = true } # test timeout
mccs-caps = { skip-tests = true } # flaky test
median_three_quicksort = { skip-tests = true } # sorting library that sometimes doesn't sort (WTF)
milagro-crypto = { skip-tests = true } # flaky test (segfaults)
mish = { skip-tests = true } # flaky test (bad math)
modbus = { skip-tests = true } # flaky test
moonlander-gp = { skip-tests = true } # may fail due to randomness
net-utils = { skip-tests = true } # depends on network
nexus-rs = { skip-tests = true } # flaky tests
nss-sys = { skip-tests = true } # flaky test (sefaults)
poolite = { skip-tests = true } # flaky test
proxy_config = { skip-tests = true } # flaky tests
read-process-memory = { skip-tests = true } # flaky tests
region = { skip-tests = true } # flaky tests
restson = { skip-tests = true } # uses HTTP requests
rspotify = { slow = true } # slow build
rustlearn = { skip-tests = true } # non-deterministic
rusty_v8 = { broken = true } # depends on network
s_app_dir = { skip-tests = true } # flaky tests
sacn = { skip-tests = true } # Tests just fail if RUST_TEST_THREADS > 1 -author
sbrsk = { skip-tests = true } # flaky tests
silk = { slow = true } # tests slow to run
simd = { broken = true } # missing feature
simple-munin-plugin = { skip-tests = true } # flaky test
slotmap = { skip-tests = true } # flaky tests
sodium-rust = { skip-tests = true } # flaky tests
structopt = { broken = true } # missing feature
sysconf = { skip-tests = true } # flaky test
tasks-framework = { skip-tests = true } # flaky tests
theban_interval_tree = { skip-tests = true } # flaky tests
tokio = { broken = true } # missing feature
tokio-periodic = { skip-tests = true } # flaky tests
tokio-rustls = { broken = true } # missing feature
touch = { skip-tests = true } # depends on the filesystem
treeflection = { skip-tests = true } # flaky test
update_rate = { skip-tests = true } # flaky tests
urdf-viz = { skip = true } # flaky build
vidar = { skip-tests = true } # flaky test
carboxyl_time = { skip-tests = true } # flaky test (timing)
cobalt = { skip-tests = true } # flaky test (timing)
conduit-hyper = { skip-tests = true } # flaky test (timing)
serialport = { skip-tests = true } # flaky test (timing)
smartpool = { skip-tests = true } # flaky test (timing)
softposit = { skip-tests = true } # flaky test (rng)
test-patience = { skip-tests = true } # flaky test (timing)
timekeeper = { skip-tests = true } # flaky test (timing)
tokio-proto = { skip-tests = true } # flaky test (concurrency)
toql_derive = { skip-tests = true } # flaky test ("Sometimes failes becuse join order different")
niftygate-asset = { skip = true } # cfg for stable/nightly, but not beta
futuredsp = { skip = true } # cfg for stable/nightly, but not beta
buildstructor = { skip-tests = true } # compiler error checks in tests
crokey = { skip-tests = true } # compiler error checks in tests
heap-vec = { skip-tests = true } # UB, sometimes segfaults
k2_tree = { skip-tests = true } # UB, sometimes segfaults

[github-repos]
# "org_name/repo_name" = { option = true }
"clinuxrulz/sodium-rust-push-pull" = { skip-tests = true } # flaky test
"euforia/rust-vivaldi" = { skip-tests = true } # flaky test
"exclave/exclave" = { skip-tests = true } # flaky test
"fromheten/plato" = { skip-tests = true } # flaky tests
"jafow/pals" = { skip-tests = true } # flaky tests
"johnedmonds/chance" = { skip-tests = true } # flaky tests
"LukeMathWalker/tracing-bunyan-formatter" = { skip-tests = true } # flaky tests
"nilsmartel/act" = { skip-tests = true } # flaky tests
"nt-ca-aqe/kitchen-kata-async-rust" = { skip-tests = true } # flaky tests
"simulacrumparty/casaubon" = { skip-tests = true } # flaky tests
"sozu-proxy/sozu" = { skip-tests = true } # flaky tests
"kellymclaughlin/rust-quickcheck-example" = { skip-tests = true } # flaky tests
"otaviopace/minigrep" = { skip-tests = true } # flaky tests
"wischli/rpaillier" = { skip-tests = true } # flaky tests
"AntonChernev/suffix-tree-search" = { skip-tests = true } # flaky tests
"0xpr03/yayd" = { skip-tests = true } # network in tests
"gclark916/vulkano_examples" = { skip = true } # spurious proc macro error
"gclark916/vulkano_tri1" = { skip = true } # spurious proc macro error
"Ayrx/binja-rs-hello-world" = { skip = true } # shared directory messed up by first build
"Ninja3047/load-symbols" = { skip = true } # shared directory messed up by first build
"etke/bff" = { skip = true } # shared directory messed up by first build
"APTy/icmp" = { skip-tests = true } # network in tests
"GothAck/rs-async-debug" = { skip-tests = true } # compiler error checks in tests
"hank-der-hafenarbeiter/imperative-rs" = { skip-tests = true } # compiler error checks in tests
"Sanchos01/weather" = { skip-tests = true } # network in tests
"appaquet/extsort-rs" = { skip-tests = true } # flaky tests
"ardeaf/redelete" = { skip-tests = true } # network in tests
"baoziv587/LoxLang" = { skip-tests = true } # flaky tests
"ciusji/eureka" = { skip-tests = true } # flaky tests
"cpard/cuckoo" = { skip-tests = true } # flaky tests (random)
"fedormatantsev/rust-components-prototype" = { skip-tests = true } # flaky tests
"naomijub/genetic-labyrinth" = { skip-tests = true } # flaky tests
"sachaarbonel/trie.rs" = { skip-tests = true } # flaky tests
"vspecky/neat-rs" = { skip-tests = true } # flaky tests

[local-crates]
